closed the workflows file

diff --git a/.github/workflows/application-service.yml b/.github/workflows/application-service.yml
--- a/.github/workflows/application-service.yml
+++ b/.github/workflows/application-service.yml
@@ -1,135 +1,135 @@
-name: CI/CD Application Service
+# name: CI/CD Application Service
 
-on:
-  push:
-    branches:
-      - main
-    paths:
-      - "packages/application/**"
+# on:
+#   push:
+#     branches:
+#       - main
+#     paths:
+#       - "packages/application/**"
 
-defaults:
-  run:
-    working-directory: packages/application
+# defaults:
+#   run:
+#     working-directory: packages/application
 
-jobs:
-  build:
-    runs-on: ubuntu-latest
+# jobs:
+#   build:
+#     runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@v4
+#     steps:
+#       - uses: actions/checkout@v4
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v4
-        with:
-          node-version: "20"
+#       - name: Set up Node.js
+#         uses: actions/setup-node@v4
+#         with:
+#           node-version: "20"
 
-      - name: Install dependencies
-        run: yarn install
+#       - name: Install dependencies
+#         run: yarn install
 
-      - name: Build the project
-        run: yarn build
+#       - name: Build the project
+#         run: yarn build
 
-      - name: Archive Production Artifact
-        uses: actions/upload-artifact@v2
-        with:
-          name: build
-          path: packages/application/build
+#       - name: Archive Production Artifact
+#         uses: actions/upload-artifact@v2
+#         with:
+#           name: build
+#           path: packages/application/build
 
-  deploy:
-    needs: build
-    runs-on: ubuntu-latest
-    steps:
-      - name: Get the Production Artifact
-        uses: actions/download-artifact@v2
-        with:
-          name: build
-          path: packages/application/build
+#   deploy:
+#     needs: build
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: Get the Production Artifact
+#         uses: actions/download-artifact@v2
+#         with:
+#           name: build
+#           path: packages/application/build
 
-      - name: Add SSH Key
-        uses: webfactory/ssh-agent@v0.5.3
-        with:
-          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
+#       - name: Add SSH Key
+#         uses: webfactory/ssh-agent@v0.5.3
+#         with:
+#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
-      - name: Ensure target directory exists
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.EC2_IP }}
-          username: ${{ secrets.EC2_USERNAME }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          port: 22
-          script: |
-            sudo mkdir -p /home/ubuntu/packages/application/build
-            sudo chown -R ubuntu:ubuntu /home/ubuntu/packages/application
+#       - name: Ensure target directory exists
+#         uses: appleboy/ssh-action@master
+#         with:
+#           host: ${{ secrets.EC2_IP }}
+#           username: ${{ secrets.EC2_USERNAME }}
+#           key: ${{ secrets.SSH_PRIVATE_KEY }}
+#           port: 22
+#           script: |
+#             sudo mkdir -p /home/ubuntu/packages/application/build
+#             sudo chown -R ubuntu:ubuntu /home/ubuntu/packages/application
 
-      - name: Copy files to EC2
-        uses: appleboy/scp-action@master
-        with:
-          host: ${{ secrets.EC2_IP }}
-          username: ${{ secrets.EC2_USERNAME }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          port: 22
-          source: "packages/application/build/*"
-          target: "/home/ubuntu"
+#       - name: Copy files to EC2
+#         uses: appleboy/scp-action@master
+#         with:
+#           host: ${{ secrets.EC2_IP }}
+#           username: ${{ secrets.EC2_USERNAME }}
+#           key: ${{ secrets.SSH_PRIVATE_KEY }}
+#           port: 22
+#           source: "packages/application/build/*"
+#           target: "/home/ubuntu"
 
-      - name: Create .env file
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.EC2_IP }}
-          username: ${{ secrets.EC2_USERNAME }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          port: 22
-          script: |
-            cat <<EOF > /home/ubuntu/packages/application/build/configs/.env
-            NODE_ENV=${{ secrets.NODE_ENV }}
-            PORT=${{ secrets.APPLICATION_PORT }}
-            MONGODB_URL=${{ secrets.MONGODB_URL }}
-            API_GATEWAY_URL=${{ secrets.API_GATEWAY_URL}}
-            LOG_LEVEL=${{ secrets.LOG_LEVEL }}
-            EOF
+#       - name: Create .env file
+#         uses: appleboy/ssh-action@master
+#         with:
+#           host: ${{ secrets.EC2_IP }}
+#           username: ${{ secrets.EC2_USERNAME }}
+#           key: ${{ secrets.SSH_PRIVATE_KEY }}
+#           port: 22
+#           script: |
+#             cat <<EOF > /home/ubuntu/packages/application/build/configs/.env
+#             NODE_ENV=${{ secrets.NODE_ENV }}
+#             PORT=${{ secrets.APPLICATION_PORT }}
+#             MONGODB_URL=${{ secrets.MONGODB_URL }}
+#             API_GATEWAY_URL=${{ secrets.API_GATEWAY_URL}}
+#             LOG_LEVEL=${{ secrets.LOG_LEVEL }}
+#             EOF
 
-      - name: Start Application
-        uses: appleboy/ssh-action@master
-        with:
-          host: ${{ secrets.EC2_IP }}
-          username: ${{ secrets.EC2_USERNAME }}
-          key: ${{ secrets.SSH_PRIVATE_KEY }}
-          port: 22
-          script: |
-            # Check if nvm is installed
-            if [ -s "$HOME/.nvm/nvm.sh" ]; then
-              source "$HOME/.nvm/nvm.sh"
-            elif [ -s "/usr/local/nvm/nvm.sh" ]; then
-              source "/usr/local/nvm/nvm.sh"
-            else
-              echo "nvm is not installed."
-              exit 1
-            fi
+#       - name: Start Application
+#         uses: appleboy/ssh-action@master
+#         with:
+#           host: ${{ secrets.EC2_IP }}
+#           username: ${{ secrets.EC2_USERNAME }}
+#           key: ${{ secrets.SSH_PRIVATE_KEY }}
+#           port: 22
+#           script: |
+#             # Check if nvm is installed
+#             if [ -s "$HOME/.nvm/nvm.sh" ]; then
+#               source "$HOME/.nvm/nvm.sh"
+#             elif [ -s "/usr/local/nvm/nvm.sh" ]; then
+#               source "/usr/local/nvm/nvm.sh"
+#             else
+#               echo "nvm is not installed."
+#               exit 1
+#             fi
 
-            # Verify yarn installation
-            if ! command -v yarn &> /dev/null; then
-              echo "Yarn could not be found"
-              exit 1
-            fi
+#             # Verify yarn installation
+#             if ! command -v yarn &> /dev/null; then
+#               echo "Yarn could not be found"
+#               exit 1
+#             fi
 
-            cd /home/ubuntu/packages/application/build
-            echo "Checking directory contents..."
-            ls -alh # Lists all files in the current directory
+#             cd /home/ubuntu/packages/application/build
+#             echo "Checking directory contents..."
+#             ls -alh # Lists all files in the current directory
 
-            # Check if server.js exists in the correct directory
-            if [ ! -f ./src/server.js ]; then
-              echo "server.js not found in ./src/"
-              exit 1
-            fi
+#             # Check if server.js exists in the correct directory
+#             if [ ! -f ./src/server.js ]; then
+#               echo "server.js not found in ./src/"
+#               exit 1
+#             fi
 
-            # Install Dependencies
-            echo "Installing dependencies..."
-            yarn install --production
+#             # Install Dependencies
+#             echo "Installing dependencies..."
+#             yarn install --production
 
-            # Check if the PM2 process is running
-            if pm2 show application > /dev/null; then
-              echo "Application is running. Restarting..."
-              pm2 restart application
-            else
-              echo "Application is not running. Starting..."
-              pm2 start src/server.js --name application
-            fi
+#             # Check if the PM2 process is running
+#             if pm2 show application > /dev/null; then
+#               echo "Application is running. Restarting..."
+#               pm2 restart application
+#             else
+#               echo "Application is not running. Starting..."
+#               pm2 start src/server.js --name application
+#             fi
